# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a91ccf8c0b2a4d7d0aaaf8fed35612b49d876a1a375b37202ad86e456677106ebdf37fe615fadaab38796b9ddb102b485d48b72481d235716366b52b1a501c5e

test:
  secret_key_base: ace78f02b8d1b2e0fe070bc6488477390e71c1ffb07d7a3b37802d55a3a6a7fc862d4aa739aae3d578c8c8bce81b4d05a00e6a849990f9ed194af64b862f6696

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
